Repository inu-appcenter/server-study-15th, pull requests merged in 2023-05, with the labels that each got.

#16 [Feat] 3주차 - Service & Controller 추가 #15
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/server-study-15th.iml
  .idea/vcs.xml
  contents/concepts/week2/junhyeong/Repository Layer 구현.md
  contents/todoListAPI/junhyung/.gitignore
  contents/todoListAPI/junhyung/build.gradle
  contents/todoListAPI/junhyung/gradle/wrapper/gradle-wrapper.jar
  contents/todoListAPI/junhyung/gradle/wrapper/gradle-wrapper.properties
  contents/todoListAPI/junhyung/gradlew
  contents/todoListAPI/junhyung/gradlew.bat
  contents/todoListAPI/junhyung/settings.gradle
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/TodoListApplication.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/config/SecurityConfig.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/config/SwaggerConfig.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/controller/TaskController.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/controller/UserController.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/BaseTimeEntity.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/task/Task.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/task/TaskRepository.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/user/User.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/user/UserEnum.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/domain/user/UserRepository.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/dto/ResponseDto.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/dto/task/TaskReqDto.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/dto/task/TaskRespDto.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/dto/user/UserReqDto.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/dto/user/UserRespDto.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/handler/CustomExceptionHandler.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/handler/aop/CustomValidationAdvice.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/handler/ex/CustomApiException.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/handler/ex/CustomNotFoundException.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/handler/ex/CustomValidationException.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/service/TaskService.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/service/UserService.java
  contents/todoListAPI/junhyung/src/main/java/appCenter/guCoding/todoList/util/CustomResponseUtil.java
  contents/todoListAPI/junhyung/src/main/resources/application-dev.yml
  contents/todoListAPI/junhyung/src/main/resources/application.yml
  contents/todoListAPI/junhyung/src/test/java/appCenter/guCoding/todoList/TaskListApplicationTests.java
  contents/todoListAPI/junhyung/src/test/java/appCenter/guCoding/todoList/domain/task/TaskRepositoryTest.java
Labels: New Feature

#18 [Feat] 3주차 - Service & Controller 추가
  contents/todoListAPI/yeongjae/todolist/.idea/dbnavigator.xml
  contents/todoListAPI/yeongjae/todolist/.idea/workspace.xml
  contents/todoListAPI/yeongjae/todolist/todolist/.gitignore
  contents/todoListAPI/yeongjae/todolist/todolist/build.gradle
  contents/todoListAPI/yeongjae/todolist/todolist/gradle/wrapper/gradle-wrapper.jar
  contents/todoListAPI/yeongjae/todolist/todolist/gradle/wrapper/gradle-wrapper.properties
  contents/todoListAPI/yeongjae/todolist/todolist/gradlew
  contents/todoListAPI/yeongjae/todolist/todolist/gradlew.bat
  contents/todoListAPI/yeongjae/todolist/todolist/settings.gradle
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/SwaggerConfig.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/TodolistApplication.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/MemberController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Member.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Todo.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/repository/MemberRepository.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/repository/TodoRepository.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/MemberService.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/TodoService.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/resources/application.properties
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/resources/application.yml
  contents/todoListAPI/yeongjae/todolist/todolist/src/test/java/com/example/todolist/TodolistApplicationTests.java
Labels: New Feature

#19 [Refactor] 3주차 - Service & Controller 추가
  contents/todoListAPI/yeongjae/todolist/todolist/build.gradle
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/config/SwaggerConfig.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/MemberController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Member.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Task.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Todo.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/TaskDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/UserDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/repository/MemberRepository.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/repository/TodoRepository.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/MemberService.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/TodoService.java
Labels: ♻️ Refactoring

#21 2주차 - Domain Layer 발표 자료 업로드
  contents/concepts/week2/eunmi/[2주차] ERD & API Docs.md
  contents/concepts/week2/eunmi/[2주차] ERD & API Docs/Untitled.png
Labels: 📘 Documentation

#24 [feat] domain, controller, service 구현
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/controller/MemberController.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/domain/BaseTimeEntity.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/domain/Member.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/domain/Todo.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/MemberDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/TodoReqDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/TodoRespDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/exception/DuplicationException.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/exception/NotFoundMemberException.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/exception/NotFoundTodoException.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/repository/MemberRepository.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/repository/TodoRepository.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/service/MemberService.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/service/TodoService.java
  contents/todoListAPI/eunmi/todolist/src/test/java/com/example/todolist/service/MemberServiceTest.java
  contents/todoListAPI/eunmi/todolist/src/test/java/com/example/todolist/service/TodoServiceTest.java
Labels: New Feature

#22 [Refactor] 3주차 - 전체 코드 수정
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Task.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/ResponseDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/TaskDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/taskdto/TaskRequestDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/taskdto/TaskResponseDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/repository/TodoRepository.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/TodoService.java
Labels: New Feature, ♻️ Refactoring

#27 [Feat] Exception Handling & User join 구현
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/MemberController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/Task.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/userdto/UserRequestDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/dto/userdto/UserResponseDto.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/exception/TodoExceptionHandler.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/exception/TodoNotFoundException.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/MemberService.java
  contents/todoListAPI/yeongjae/todolist/todolist/src/main/java/com/example/todolist/service/TodoService.java
Labels: New Feature, ♻️ Refactoring

#29 [Feat] Domain, Controller, Service 추가
  contents/todoListAPI/wonjeong/HELP.md
  contents/todoListAPI/wonjeong/mvnw
  contents/todoListAPI/wonjeong/mvnw.cmd
  contents/todoListAPI/wonjeong/pom.xml
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/AppCenterSpringbootApplication.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/config/SwaggerConfig.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/MemberController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/TodolistController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/MemberDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/TodolistDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/request/ChangeMemberDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/MemberResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/TodolistResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Member.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Todolist.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/repository/MemberRepository.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/repository/TodolistRepository.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/MemberService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/TodolistService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/MemberServiceImpl.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/TodolistServiceImpl.java
  contents/todoListAPI/wonjeong/src/main/resources/application.properties
  contents/todoListAPI/wonjeong/src/main/resources/logback-spring.xml
  contents/todoListAPI/wonjeong/src/test/java/com/appcenter/AppCenterSpringbootApplicationTests.java
  contents/todoListAPI/wonjeong/target/classes/application.properties
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/AppCenterSpringbootApplication.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/config/SwaggerConfig.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/controller/MemberController.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/controller/TodolistController.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/MemberDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/TodolistDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/request/ChangeMemberDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/response/MemberResponseDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/response/TodolistResponseDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/entity/Member.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/entity/Todolist.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/repository/MemberRepository.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/repository/TodolistRepository.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/MemberService.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/TodolistService.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/impl/MemberServiceImpl.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/impl/TodolistServiceImpl.class
  contents/todoListAPI/wonjeong/target/classes/logback-spring.xml
Labels: New Feature

#33 [Develop, Refactor] TodoList 기능 추가 및 리펙터링
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/controller/MemberController.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/controller/TodoController.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/domain/Member.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/domain/Todo.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/MemberDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/MemberPageRespDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/TodoCheckReqDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/TodoPageRespDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/dto/TodoReqDto.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/service/MemberService.java
  contents/todoListAPI/eunmi/todolist/src/main/java/com/example/todolist/service/TodoService.java
  contents/todoListAPI/eunmi/todolist/src/test/java/com/example/todolist/service/MemberServiceTest.java
  contents/todoListAPI/eunmi/todolist/src/test/java/com/example/todolist/service/TodoServiceTest.java
Labels: New Feature, ♻️ Refactoring

#34 [Chore, Refactor] 1차 개선사항
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/Appcenter-Springboot.main.iml
  contents/todoListAPI/wonjeong/build.gradle
  contents/todoListAPI/wonjeong/gradle/wrapper/gradle-wrapper.jar
  contents/todoListAPI/wonjeong/gradle/wrapper/gradle-wrapper.properties
  contents/todoListAPI/wonjeong/gradlew
  contents/todoListAPI/wonjeong/gradlew.bat
  contents/todoListAPI/wonjeong/pom.xml
  contents/todoListAPI/wonjeong/settings.gradle
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/MemberController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/TodolistController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/MemberDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/TodolistDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/request/ChangeMemberDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/MemberResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/TodolistResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Member.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Todolist.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/MemberService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/TodolistService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/MemberServiceImpl.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/TodolistServiceImpl.java
  contents/todoListAPI/wonjeong/src/main/resources/application.properties
Labels: 🧹 Clean Up, ♻️ Refactoring

#43 [Fix] 충돌 해결
  .gitignore
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/uiDesigner.xml
  contents/todoListAPI/wonjeong/build.gradle
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/MemberController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/controller/TodolistController.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/request/MemberRequestDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/request/TodolistRequestDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/MemberResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/dto/response/TodolistResponseDTO.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Member.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/entity/Todolist.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/data/repository/MemberRepository.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/MemberService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/TodolistService.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/MemberServiceImpl.java
  contents/todoListAPI/wonjeong/src/main/java/com/appcenter/service/impl/TodolistServiceImpl.java
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/AppCenterSpringbootApplication.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/config/SwaggerConfig.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/controller/MemberController.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/controller/TodolistController.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/MemberDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/TodolistDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/request/ChangeMemberDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/response/MemberResponseDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/dto/response/TodolistResponseDTO.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/entity/Member.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/entity/Todolist.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/repository/MemberRepository.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/data/repository/TodolistRepository.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/MemberService.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/TodolistService.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/impl/MemberServiceImpl.class
  contents/todoListAPI/wonjeong/target/classes/com/appcenter/service/impl/TodolistServiceImpl.class
Labels: 🧹 Clean Up
